---
title: "Publications"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Peer-reviewed

### 2022

**Micheli, L.**, Negrini, M., Schuhmann, T., \& Riedl, A. (2022). Brain stimulation reveals distinct motives underlying reciprocal punishment and reward. *In Press at Proceedings of the Royal Society B.*

Azevedo, F., **Micheli, L.**, \& Bolesta., D. S. Does Stereotype Threat contribute to the Political Knowledge Gender Gap? A Preregistered Replication Study of Ihme and Tausendpfund (2018). Conditionally accepted at *Journal of Experimental Political Science*.

Azevedo, F., Marques, T., \& **Micheli, L.** (2022). In pursuit of racial equality: Identifying the determinants of support for the Black Lives Matter Movement with a systematic review and multiple meta-analyses. *Perspectives on Politics,* 1-23. [(link)](https://doi.org/10.1017/S1537592722001098)

<aside>
<div data-badge-type="donut" data-doi="10.1017/S1537592722001098" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Azevedo, F., Liu, M., Pennington, C. R., Pownall, M., Evans, T. R., Parsons, S., Elsherif, M., **Micheli, L.**, Westwood, S., \& FORRT. (2022). Towards a culture of open scholarship: The role of pedagogical communities. *BMC Research Notes, 15*(75).[(link)](https://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-022-05944-1) | [(Preprint)](https://osf.io/preprints/metaarxiv/ek9m5) 

<aside>
<div data-badge-type="donut" data-doi="10.1186/s13104-022-05944-1" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>


Parsons, S., Azevedo, F., Elsherif, M. M., Guay, S., Shahim, O. N., Govaart, G. H., Norris, E.,  ... **Micheli, L.**, \& Aczel, B. (2022). A Community-Sourced Glossary of Open Scholarship Terms. *Nature Human Behavior.* [(link)](https://doi.org/10.1038/s41562-021-01269-4) | [(preprint)](https://osf.io/preprints/metaarxiv/kdqcw)
*[Team Science Contributorship: Resources; Writing: review and editing]* 

<aside>
<div data-badge-type="donut" data-doi="10.1038/s41562-021-01269-4" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Psychological Science Accelerator Self-Determination Theory Collaboration (2022). A Global Experi-
ment on Motivating Social Distancing During the COVID-19 Pandemic. *PNAS, 119*(22), e2111091119. [(link)](https://doi.org/10.1073/pnas.2111091119) | [(preprint)](https://psyarxiv.com/n3dyf/) *[Team Science Contributorship: Resources; Writing: review and editing]* 

<aside>
<div data-badge-type="donut" data-doi="10.1073/pnas.2111091119" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2021

**Micheli, L.**, Stallen, M., \& Sanfey, A.G. (2021). The effect of centralized financial and social incentives on cooperative behavior and its underlying neural mechanisms. *Brain Sciences, 11(3)*, 317. [(link)](https://doi.org/10.3390/brainsci11030317) | [(data)](https://data.donders.ru.nl/?1)

<aside>
<div data-badge-type="donut" data-doi="10.3390/brainsci11030317" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Wang K., Goldenberg A., Dorison, C.A., Miller, J.K., Uusberg, A., Lerner, J.S., Gross, J.J., ... **Micheli, L.**, ... \& Moshontz, H. (2021). A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. *Nature Human Behavior 5*, 1089–1110. [(link)](https://doi.org/10.1038/s41562-021-01173-x)   
*[Team Science Contributorship: Resources; Writing: review and editing]*   
  
<aside>
<div data-badge-type="donut" data-doi="10.1038/s41562-021-01173-x" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>


### 2020

**Micheli, L.** \& Gagnon, N.(2020). Unequal chances: Ex ante fairness and individual control. *Scientific Reports, 10*, 21862. [(link)](https://doi.org/10.1038/s41598-020-78335-w).  

<aside>
<div data-badge-type="donut" data-doi="10.1038/s41598-020-78335-w" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>  


Tierney, W., Hardy, J. H. III., Ebersole, C., Leavitt, K., Viganola, D., Clemente, E., Gordon, M., Dreber, A.A., Johannesson, M., Pfeiffer, T., Hiring Decisions Forecasting Collaboration, \& Uhlmann, E.L. (2020). Creative destruction in science. *Organizational Behavior and Human Decision Processes, 161*, 291-309. [(link)](https://doi.org/10.1016/j.obhdp.2020.07.002}).      
*[Team Science Contributorship: Member of Forecasting Collaboration]*   

<aside>
<div data-badge-type="donut" data-doi="10.1016/j.obhdp.2020.07.002" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>


### 2019

Huijsmans, I., Ma, I., **Micheli, L.**, Civai, C., Stallen, M., \& Sanfey, A.G. (2019). A scarcity mindset alters neural processing underlying value-based decision making. *PNAS, 116*(24), 11699-11704. [(link)](https://doi.org/10.1073/pnas.1818572116)

<aside>
<div data-badge-type="donut" data-doi="10.1073/pnas.1818572116" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

## Under Review

**Micheli, L.**, Breil, C., \& Böckler, A. Golden gazes: Gaze direction and emotional context promote prosocial behavior by increasing attributions of empathy and perspective-taking [(Preregistration)](https://osf.io/8ey4f) 

<div style="text-align: justify"> Prosocial behavior is fundamental to societies. But when and towards whom do humans act generously? We investigate the impact of a conversation partner’s gaze direction and the emotional context on (i) perceptions of their social cognition skills and (ii) prosocial decisions towards them. In three experiments (two preregistered, N = 486), participants witnessed pre-recorded video conversations between a listener (visible) and a speaker (audible, not visible). The listener either established eye contact, averted gaze or showed a mixed gaze pattern (gaze direction) while the speaker told a neutral or negatively-valenced autobiographic episode (emotional context). Participants rated the listener’s empathy and perspective-taking after each video and played the Trust Game (study 1) or the Dictator Game (study 2) with the listener. Replicating previous findings, occasional gaze avoidance, especially during negative narrations, increased attributions of social understanding to the listener. Critically, mediation analyses revealed that listeners perceived as empathic and taking perspective were ultimately treated with more trust and generosity in strategic and non-strategic economic games, suggesting that social signals and contextual cues can serve as an indication of another’s reputation, thereby promoting indirect reciprocity. Lastly, in study 3, we show that emotional context, but not listeners’ gaze behavior, promoted the spread of generosity towards anonymous, previously unobserved individuals in a Dictator Game, driven by social cognition skills attributed to the listener. We conclude that social signals and contextual cues can be important drivers of cooperation in societies via mechanisms such as indirect reciprocity and social contagion of generosity. </div>    

<br>

Schumacher, A., \& **Micheli, L.** Anticipated scarcity and stockpiling during the COVID-19 pandemic: The role of perceived threat, childhood SES and materialism. 

<div style="text-align: justify">Previous research has shown that perceived existential threat experienced during or shortly after the first wave of the global COVID-19 pandemic, engendered anticipated scarcity and stockpiling behavior. However, the relationship between anticipated scarcity and stockpiling may not hold unambiguously for everyone. Across two exploratory and one preregistered study (N=644), we show that perceived threat of COVID-19 is associated with stockpiling tendencies by increasing the anticipation of product scarcity – a resource threat. The association between anticipated product scarcity and stockpiling depends, however, on childhood socio-economic status (SES) and materialism. For individuals with low childhood SES, the anticipation of product scarcity was only associated with stockpiling among those who valued materialism. Individuals with high childhood SES, by contrast, stockpiled in response to anticipated scarcity regardless of their level of materialism. Our findings qualify previous literature on the association between perceived threat of COVID-19, anticipated scarcity and stockpiling during the COVID-19 pandemic and help reconcile contradictory predictions about the role of childhood SES in individuals’ consumption behavior in response to adversity.</div>

## In Preparation

**Micheli, L.**, Geyskens, K., Goukens, C., \& Riedl, A. More opportunities, better outcomes: Does inequality in opportunity call for outcome redistribution? 

<div style="text-align: justify">The rise of economic inequality has brought to light the debate of unequal opportunities in societies. While the demand for levelling the playing field is currently high, it is less clear how inequality in opportunity should be rectified. Here, we explore whether outcome redistribution is seen as a legitimate compensation for unequal opportunities. In doing so, we examine the behavior of both involved and non-involved individuals (i.e., stakeholders and spectators). In an experimental setting, stakeholders received either high or low chances to win a monetary prize. Before knowing who the winner was, stakeholders were asked to report how they would redistribute the monetary prize in case they were themselves the winner while spectators were asked how they would redistribute the prize in case a person with high or low chances was the winner. The source of inequality in opportunities was varied. Results show that stakeholders with higher winning chances felt more entitled to the monetary prize and redistributed less of it than stakeholders with low winning chances. Moreover, source of inequality differentially influenced ex ante redistribution of stakeholders with high and low winning chances. Spectators' ex ante redistributive decisions were neither influenced by individuals' chances nor by the source of inequality. Results are discussed in light of possible implications to redistributive policies that aim to address inequality in opportunities.</div>

<br>
**Micheli, L.**, Geyskens, K., Briers, B., \& Goukens, C. Climbing the ladder: Perceptions of high upward economic mobility increase status consumption among bottom-tier consumers. 

<div style="text-align: justify"> Beliefs in upward economic mobility are prevalent in many societies and especially pervasive among the poor. This research focuses on bottom-tier consumers—and examines how beliefs in upward mobility affect status seeking and the likelihood to engage in conspicuous consumption. Because perceptions of high economic mobility enhance the perceived legitimacy of inequality and thus the credibility of status goods, bottom-tier consumers are expected to become more prone to signal their status under high rather than low economic mobility. Four studies provide evidence for this hypothesis across various measures of status consumption and show the underlying process through perceived legitimacy of inequality. The effect of perceptions of upward mobility on preference for status consumption is independent of the perceived level of economic inequality and only present when income is not directly observable, suggesting that status consumption is used to signal one’s income. The present research sheds light on the importance of investigating societal perceptions among the poor to understand consumer behavior and offers implications for policy making.</div>

<br>

## Work in Progress

**Micheli, L.**, \& Böckler, A. Effects of gaze direction and face visibility on third-party punishment and compensation. [(Preregistration)](https://osf.io/9myx6)

**Micheli, L.**, Okamoto-Barth, S., Goebel, R., \& Riedl, A. The neural mechanisms of positive and negative reciprocity: two sides of the same coin?



